{
 "title": "MotoShop Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Most wanted products",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "most_wanted_products{}", "legendFormat": "{{brand}} {{model}}" }
   ]
  },
  {
   "title": "Most Wanted Yamaha",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "most_wanted_products{brand=\"Yamaha\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Routes history",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_total_by_id{}", "legendFormat": "{{method}} /product{{path}}" }
   ]
  },
  {
   "title": "Most wanted Brand",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "most_wanted_products{brand=~\"BMW|Yamaha\"}",
     "legendFormat": "{{brand}} {{model}}"
    }
   ]
  }
 ]
}